development:
  adapter: postgresql
  encoding: unicode
  database: stringer_dev
  pool: 5
  username: your_username
  password: your_password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: stringer_test
  pool: 5
  username: your_username
  password: your_password
  host: localhost
  port: 5432

production:
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: <%= Integer(ENV.fetch("DB_POOL", 15)) %>
